### ISSUE TITLE
Add permissions guide to readme

### ISSUE THREAD

**Issue by maxcodeshere** [YannickFricke/Satisfactory-DS-Docker#6]
Thank you for maintaining this project!

Depending on the level of knowledge a user professes, it might be usefull to add a small section on how to correctly set up permissions for the bind mounts on the host FS.

Let me know what you think and if you want me to create a PR :)

**Comment by YannickFricke** [comment]
Hey Max

Thanks for the kind words! :)

Do you mean the host file permissions in relation to the `steam` user which is created when the container is built?
If yes that would be awesome! :)

**Comment by maxcodeshere** [comment]
Hi Yannick,

yes that is exactly what I meant. So basically just `chown 1000:1000 /saved`. But for beginners it might simplify things _a lot_.

I'll get the PR ready during the weekend :)

**Comment by YannickFricke** [comment]
Awesome! Thanks in advance! :)
