### ISSUE TITLE
GitHub update check is disabled

### ISSUE THREAD

**Issue by ekeih** [YannickFricke/Satisfactory-DS-Docker#8]
Thanks for this awesome project!

GitHub disabled the update check action two weeks ago as shown at https://github.com/YannickFricke/Satisfactory-DS-Docker/actions/workflows/update.yml
> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs. 

Could you enable that again so the action builds a new image for the current upstream release?

Thanks

**Comment by ekeih** [comment]
In case someone else comes across this issue and is looking for newer images, I created a new project that automatically builds early access and experimental images based on the same Dockerfile: https://github.com/ekeih/satisfactory-bot

Feel free to use those images and let me know if you run into issues.

**Comment by YannickFricke** [comment]
@ekeih Heya! Sorry for the really late response!
I have enabled it again :)
