### ISSUE TITLE
Possible to have an updated docker with an updated server version

### ISSUE THREAD

**Issue by alien999999999** [YannickFricke/Satisfactory-DS-Docker#9]
Hey, I've chosen your image, because i'm trying to run this in a no-internet LAN; first, my client was too old (no network support), now I've finally gotten it updated to 0.7.1.1 and now when i try to connect, it says server version mismatch of course. would it be possible to provide an updated docker image for this version, It would be easier to copy docker image exports back and forth, rather then trying to move the server to somewhere there is internet and update it.
Thanks in advance!

**Comment by ekeih** [comment]
Based on the silence in https://github.com/YannickFricke/Satisfactory-DS-Docker/issues/8 I don't think there will be any updates of this image anymore.

A while ago I started to build my own image. It is based on the same Dockerfile and should work as a replacement for you as well. If you are interested you can find it here: https://github.com/ekeih/satisfactory-bot/pkgs/container/satisfactory-bot%2Fserver-public
There is also an image for the experimental releases available in the same repo. New images are usually available 5-15 minutes after the official releases.

**Comment by alien999999999** [comment]
> Based on the silence in #8 I don't think there will be any updates of this image anymore.
> 
> A while ago I started to build my own image. It is based on the same Dockerfile and should work as a replacement for you as well. If you are interested you can find it here: https://github.com/ekeih/satisfactory-bot/pkgs/container/satisfactory-bot%2Fserver-public There is also an image for the experimental releases available in the same repo. New images are usually available 5-15 minutes after the official releases.

Thanks, any idea if you have an image that has server version matching this game client version 211839 ?

**Comment by ekeih** [comment]
Looking at https://www.reddit.com/r/SatisfactoryGame/comments/zk0evu/patch_notes_early_access_v0711_build_211839/ I think your version is the latest early access version from 19 days ago.

The matching image would be the latest one from here: https://github.com/ekeih/satisfactory-bot/pkgs/container/satisfactory-bot%2Fserver-public/58400438?tag=2022.12.12-10115591

No promises, but I think that should match your client version.

**Comment by YannickFricke** [comment]
@alien999999999 Heya! Sorry for the late response! I have reenabled the workflow so it should now update every time when there is an Steam update again :)

@ekeih
> Based on the silence in https://github.com/YannickFricke/Satisfactory-DS-Docker/issues/8 I don't think there will be any updates of this image anymore.

Not gonna lie, had much work to do at regular work and uncountable GH issues filled my daily inbox :)

The bad thing about GitHub is, that they disable the workflow automatically after 60 days of repository inactivity... Normally the workflow should have been triggered every hour to look for new updates. So I am looking for a way where we can trick GitHub into thinking a normal person has pushed something instead of an bot account (like the `Github Actions` user - I bet they detect this).

**Comment by alien999999999** [comment]
yeah, no worries, i know the feeling, i was helped by ekeih; and I was able to have a full offline LAN setup after some fiddling, i'm no longer updating either client or server now that it works, since they are not connected to internet anyway...
